  - name: take vars for el-like
    include_vars: "{{ ansible_os_family|lower }}"

  - name: make sure apache is installed
    ansible.builtin.package:
      name: "{{apache_package}}"
      state: present

  - name: make sure httpd service is running and activated 
    ansible.builtin.service:
      name: "{{apache_service}}"
      enabled: yes
      state: started

  - name: make sure apache has helloworld file
    ansible.builtin.copy:
      src: index.html
      dest: "/var/www/html/index.html"

  - name: make sure firewalld is installed
    ansible.builtin.package:
      name: "{{firewall_package}}"
      state: present

  - name: make sure firewalld service is running and activated
    ansible.builtin.service:
      name: "{{firewall_service}}"
      enabled: yes
      state: started

  - name: make sure https traffic is allowed
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: make sure http traffic is allowed
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: make sure firewalld is reloaded after fw changes
    ansible.builtin.service:
      name: firewalld
      enabled: yes
      state: reloaded


