---
- name: stopped and removed web server
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  hosts: all

  tasks:

  - name: make sure httpd service is stopped and disabled
    ansible.builtin.service:
      name: "{{apache_service}}"
      enabled: no
      state: stopped

  - name: make sure apache is removed
    ansible.builtin.package:
      name: "{{apache_package}}"
      state: absent

  - name: make sure helloworld file is removed
    ansible.builtin.file:
      path: "/var/www/html/index.html"
      state: absent

  - name: make sure firewalld is installed
    ansible.builtin.package:
      name: "{{firewall_package}}"
      state: present

  - name: make sure firewalld service is running and activated
    ansible.builtin.service:
      name: "{{firewall_service}}"
      enabled: yes
      state: started

  - name: make sure traffic for https is denied
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: disabled

  - name: make sure traffic for http is denied
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: disabled

  - name: make sure firewalld is reloaded after fw changes
    ansible.builtin.service:
      name: firewalld
      enabled: yes
      state: reloaded


