---
- name: playbook1 create web server
  become: yes
  become_method: su
  become_user: root

  tasks:
  - name: install httpd
    ansible.builtin.package:
      name: "{{apache_package}}"
      state: latest

  - name: bring httpd service to running and activated state
    ansible.builtin.service:
      name: httpd
      enabled: yes
      state: started

  - name: create helloworld for apache
    ansible.builtin.copy:
      dest: "/var/www/html/index.html"
      content: “Welcome to my web server”

  - name: install firewalld
    ansible.builtin.package:
      name: "{{firewall_package}}"
      state: latest

  - name: bring firewalld service to running and activated state
    ansible.builtin.service:
      name: firewalld
      enabled: yes
      state: started

  - name: permit traffic in default zone for http and https service
    ansible.posix.firewalld:
      service: http,https
      permanent: yes
      state: enabled

